create table users (
    id bigint generated by default as identity,
    username varchar(255) not null unique,
    email varchar(255) not null unique,
    password varchar(255),
    enabled boolean not null default false,
    auth_provider varchar(255) not null check (auth_provider in ('LOCAL','GOOGLE')),
    provider_id varchar(255) unique,
    created_at timestamp(6) not null,
    phone_number varchar(20) unique,
    role varchar(255) not null check (role in ('CUSTOMER','ORGANIZER','ADMIN')),
    primary key (id)
);

create table categories (
    id bigint generated by default as identity,
    name varchar(255) not null unique,
    primary key (id)
);

create table locations (
    id bigint generated by default as identity,
    name varchar(255) not null unique,
    address varchar(255),
    city varchar(255),
    latitude double precision,
    longitude double precision,
    primary key (id)
);

create table events (
    id bigint generated by default as identity,
    title varchar(255) not null,
    description text,
    created_at timestamp(6) not null,
    date timestamp(6) not null,
    organizer_id bigint not null,
    location_id bigint not null,
    thumbnail_url text,
    deleted boolean not null default false,
    primary key (id)
);

create table event_categories (
    event_id bigint not null,
    category_id bigint not null,
    primary key (event_id, category_id)
);

create table refresh_tokens (
    id bigint generated by default as identity,
    user_id bigint not null,
    token varchar(256) not null unique,
    expires_at timestamp(6) not null,
    revoked boolean not null default false,
    created_at timestamp(6) not null,
    primary key (id)
);

create table verification_tokens (
    id bigint generated by default as identity,
    user_id bigint not null,
    token varchar(256) not null unique,
    expires_at timestamp(6) not null,
    created_at timestamp(6) not null,
    used_at timestamp(6),
    primary key (id)
);

alter table if exists events
    add constraint fk_event_organizer
    foreign key (organizer_id)
    references users
    on delete cascade;

alter table if exists events
    add constraint fk_event_location
    foreign key (location_id)
    references locations;

alter table if exists event_categories
    add constraint fk_event_categories_event
    foreign key (event_id)
    references events
    on delete cascade;

alter table if exists event_categories
    add constraint fk_event_categories_category
    foreign key (category_id)
    references categories
    on delete cascade;

alter table if exists refresh_tokens
    add constraint fk_refresh_token_user
    foreign key (user_id)
    references users
    on delete cascade;

alter table if exists verification_tokens
    add constraint fk_verification_token_user
    foreign key (user_id)
    references users
    on delete cascade;
