create table orders (
    sub_total_amount numeric(38,2) not null,
    total_amount numeric(38,2) not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) not null,
    user_id bigint not null,
    order_number varchar(32) not null unique,
    status varchar(255) not null check (status in ('DRAFT','PENDING','CONFIRMED','CANCELLED','COMPLETED','REFUNDED')),
    primary key (id)
);

create table tickets (
    checked_in_at timestamp(6),
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    order_id bigint not null,
    ticket_type_id bigint not null,
    ticket_number varchar(32) not null unique,
    email varchar(255) not null,
    qr_code varchar(255) not null unique,
    seat_info TEXT,
    status varchar(255) not null check (status in ('VALID','USED')),
    primary key (id)
);

create table ticket_types (
    max_purchase integer not null check (max_purchase>=1),
    price numeric(10,2) not null,
    quantity_reserved integer not null check (quantity_reserved>=0),
    quantity_sold integer not null check (quantity_sold>=0),
    quantity_total integer not null check (quantity_total>=1),
    event_id bigint not null,
    id bigint generated by default as identity,
    sale_end_time timestamp(6) not null,
    sale_start_time timestamp(6) not null,
    description TEXT,
    name varchar(255) not null,
    primary key (id)
);


alter table if exists orders
    add constraint fk_order_user
    foreign key (user_id)
    references users
    on delete cascade;

alter table if exists tickets
    add constraint fk_ticket_order
    foreign key (order_id)
    references orders;


alter table if exists tickets
    add constraint fk_ticket_type
    foreign key (ticket_type_id)
    references ticket_types;

alter table if exists ticket_types
    add constraint fk_ticket_event
    foreign key (event_id)
    references events
    on delete cascade;

