create table order_items (
    id bigint generated by default as identity,
    order_id bigint not null,
    ticket_type_id bigint not null,
    quantity integer not null check (quantity >= 1),
    unit_price numeric(10,2) not null check (unit_price >= 0),
    line_total numeric(10,2) not null check (line_total >= 0),
    primary key (id)
);

alter table if exists order_items
    add constraint fk_order_item_order
    foreign key (order_id)
    references orders
    on delete cascade;

alter table if exists order_items
    add constraint fk_order_item_ticket_type
    foreign key (ticket_type_id)
    references ticket_types;

alter table if exists orders
    add column if not exists contact_email varchar(255);

update orders
set contact_email = (
    select u.email
    from users u
    where u.id = orders.user_id
)
where contact_email is null;

alter table if exists orders
    alter column contact_email set not null;
